# Generated by Django 4.0.6 on 2022-08-02 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=10, null=True)),
                ('account_name', models.CharField(max_length=25, null=True)),
                ('savings', models.IntegerField()),
                ('destination', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Issued', models.DateField(default=django.utils.timezone.now)),
                ('card_status', models.CharField(max_length=24, null=True)),
                ('signature', models.ImageField(upload_to='')),
                ('issuer', models.CharField(max_length=24, null=True)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('card_name', models.CharField(max_length=24, null=True)),
                ('card_type', models.CharField(max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('symbol', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=14, null=True)),
                ('age', models.SmallIntegerField()),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
                ('pin', models.IntegerField()),
                ('marital_status', models.CharField(max_length=10, null=True)),
                ('signature', models.ImageField(upload_to='')),
                ('employment_status', models.CharField(max_length=10, null=True)),
                ('id_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_identifier', models.CharField(max_length=24, null=True)),
                ('Sent_on', models.DateField(default=django.utils.timezone.now)),
                ('Received_at', models.DateField(default=django.utils.timezone.now)),
                ('Delivered_on', models.DateField(default=django.utils.timezone.now)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('transaction_cost', models.IntegerField()),
                ('status', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.IntegerField()),
                ('pin', models.SmallIntegerField()),
                ('active', models.BooleanField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=24, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_card', to='wallet.card')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_currency', to='wallet.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=24, null=True)),
                ('account_origin', models.CharField(max_length=24, null=True)),
                ('destination', models.CharField(max_length=25, null=True)),
                ('dateTime', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=24, null=True)),
                ('third_Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_third_party', to='wallet.third_party')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_file', models.FileField(upload_to='wallet/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=24, null=True)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateField(default=django.utils.timezone.now)),
                ('loan_terms', models.CharField(max_length=24, null=True)),
                ('payment_dueDate', models.DateField(default=django.utils.timezone.now)),
                ('guaranter', models.CharField(max_length=24, null=True)),
                ('balance', models.CharField(max_length=24, null=True)),
                ('duration', models.CharField(max_length=24, null=True)),
                ('interest_rate', models.IntegerField()),
                ('stutus', models.CharField(max_length=24, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Account_card', to='wallet.card'),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
    ]
