# Generated by Django 4.1 on 2022-10-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='signature',
        ),
    ]
